### PR TITLE
Introduce protected method WordpressClient::_performRequest() that can be overridden

### PR DESCRIPTION
**Pull request by igorwwwwwwwwwwwwwwwwwwww**

### CODE REVIEW

**Comment by letrunghieu** [comment]
Can you change the name of the method, we do not use the underscore `_` in the beginning of a protected method.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
@letrunghieu done!

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Thank you @letrunghieu.

**Comment by letrunghieu** [comment]
@igorwwwwwwwwwwwwwwwwwwww I have released a new tag with your updates, too.

**Pull request merged**
